# Fruit Prediction Using Random Forest

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.model_selection import RandomizedSearchCV

In [2]:
df=pd.read_table("fruits.txt")

In [3]:
df

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70

In [4]:
x=df.iloc[:,3:6]

In [5]:
x.head()

   mass  width  height
0   192    8.4     7.3
1   180    8.0     6.8
2   176    7.4     7.2
3    86    6.2     4.7
4    84    6.0     4.6

In [6]:
y=df.iloc[:,0:1]

In [7]:
fruits=dict(zip(df.fruit_label.unique(),df.fruit_name.unique()))
fruits

{1: 'apple', 2: 'mandarin', 3: 'orange', 4: 'lemon'}

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1)

In [25]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [26]:
y_train

    fruit_label
10            1
51            4
26            3
55            4
30            3
41            3
48            4
27            3
46            4
57            4
31            3
13            1
22            1
50            4
32            3
17            1
54            4
33            3
23            1
4             2
14            1
29            3
28            3
53            4
42            3
18            1
58            4
20            1
25            3
6             2
45            4
7             2
56            4
1             1
16            1
0             1
15            1
5             2
11            1
9             1
8             1
12            1
43            4
37            3

# Starting Hyper Parameter Tuning

In [11]:

# scaling data
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

# define models
ridge = linear_model.Ridge()
lasso = linear_model.Lasso()
elastic = linear_model.ElasticNet()
lasso_lars = linear_model.LassoLars()
bayesian_ridge = linear_model.BayesianRidge()
logistic = linear_model.LogisticRegression(solver='liblinear')
sgd = linear_model.SGDClassifier()

In [12]:
loss = ['hinge', 'log', 'modified_huber', 'squared_hinge', 'perceptron']
penalty = ['l1', 'l2', 'elasticnet']
alpha = [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000]
learning_rate = ['constant', 'optimal', 'invscaling', 'adaptive']
class_weight = [{1:0.5, 0:0.5}, {1:0.4, 0:0.6}, {1:0.6, 0:0.4}, {1:0.7, 0:0.3}]
eta0 = [1, 10, 100]

param_distributions = dict(loss=loss,
                           penalty=penalty,
                           alpha=alpha,
                           learning_rate=learning_rate,
                           class_weight=class_weight,
                           eta0=eta0)

random = RandomizedSearchCV(estimator=sgd,
                            param_distributions=param_distributions,
                            scoring='roc_auc',
                            verbose=1, n_jobs=-1,
                            n_iter=1000)

In [ ]:
y_train

In [ ]:
y_test

In [ ]:
clf1=model.score(x_test,y_test)
clf

In [ ]:
val=model.predict([[132,5.8,8.7]])

In [ ]:
val

In [ ]:
fruits[4]

In [ ]:
model2.score(x_test,y_test)